sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: B6Z3ojk2JuR8OR48wzcFqMgY0hNs4+7amyYbN1p5WlQlOU9oNisqtDWqRDcRqYHN9sPfO4RQzHBFCJFj3FVBmeFA6FBrQHEYT7CXamr2ExRJzRQFS+iizbBEj2rm13mjYZY+LnnBy4ApOZFfnGnQ8NNrPySVjF8yf1MdZ5KrpTgwufPETEYAIn+rVODwWt9GG7dG6ccViNroEcTuJeTC1+20HJh3+noAlhVT5NeYRL/tlrsNJsvgIt8uG/jVdnOLlXW+RWKq/nOvL8r7eepoC2BfCibcBJpiwoI2O8mw3g57RdJQS7mt+j2Sz1ZFsnr9prwJsL6NlPTSzsVvvnNORFfUHY/MJyJvWzS6SPOTVnDmZHC2RmG5wALxHJMTX70wFB0yrxciR4d6OAm87so1ke5Aix7S5Plqflnnq87wzR6lDJXtAbYNFpUAv6g6SQB8bM/AB5YO/jfyuZH/LihhgdbXNMUsk06JRRo5DsJbVo63DbKAeSlJe27JKuek5ZCE3VgA8jnxRjgAi705y4gb4z3BuYoNRNoIxuOLvv1P4/8803c6jr6bCFBayN6v36peQwQUFaHQzLhosq/IPqmUHw2Fvteusl4h3Wxate3Y0cCM0ic3B8zzuH+N1IRJa9ymF8SRyWuqfMPcawqdKYmp6SgDaTnKbmqevzQ2d9YhhjQ=
  - secure: fBnUBHG88R7zeNDQevfkdrVKjTdDjxY9aq84UYzOttBnNsSDQuq2qLJwjEA52EctV73OKrMlbd1qDysKh6rMBr0BtvLnNo/N9CqwxMvBOX2Z5quaBogbZVopbpqjz2mXu3DD0UVSvL+/i9QbISsgt5WfTWk3+ppOz6pEtoAV6zYoecz/vOWrTVaVG+EHuLCnu9kBhXSu8gsMxCVezzubEGVtv4VqpAt0gTPnWRR8Z5ZE3IDlaE2bD6DvSubrmZGXsJEsGsdDdhzfBFQVa18ffGCLo3KpXrBLBH6neVn43kriBTglRt4E/L+paTq170AYl2jmnVcS0pu7L6cOYUYVhhu/xNOTVDo3jPgWGxOgD34jghnHFE36YWoUa5yoGqRBTMWA4Dm+E1Jqv4itniurn5ebxo0eKsLT7hIY9XjUNifQ3v4xBk96zg7VvUEHSL4qBSO511qYG8GR+wIJSyZVt8X2AMWXRKYvzShCGhFZAYiU7DflZ6ws86t6e+Xhbts+aU/1+roLUPIRVKMCOFfWWwTltJCowwfRcJR9Cvpal97NfoqpuwO2D/j+si2V4Yinbj/BQQRpsOp6Uo17nhOoLAEbee5BEFe0kO3WmjHrHBmsUd8X8FmiAfGvli5Bku8BCFiU6XEClCekuLCNPKXWWhl/ZQEtFbb8zsb2TeT/Z8U=
  - secure: VbaMIlSKG7bM2UEUEk46u1g9RTzmyz7F45reQSvCUPi1UQ/vbREAe0akXNGkWo1pOR71Ia5efkb1fGWwTORi0pslauyRzpF3MHBoCjVmT+4wxlgigpSK31gaRGWR4Yey1MBOHkC/mj08MYCRK18PKe8WX2J3KmnQTS94yTbx9FGeo+BLMuLEu9mWXYs2FUAvS1RTntL2fg3fSXnclLHFzBxw2MSI3+QL7McI5OdyYpOM+aECcGmRi1b3KhcFVJ5OcFl5EMaH0qH07avFrUnvoF+38iyY6j3ocB7mfqmvQHPvOLEW2mJ7VMXbpJkA/DKUqioHFNWqdG6Epg0c3mOernAev1a7NfLGr314N+uzoaG/01DpN4SAYahszZtKfV9fDdCYwHy0Z6Vh8D78FGGh1r+Yn2nwd4gx3M9yVDn/C4rxQLu9Q0pYpi14tE8PBNDARZ6EbcQgOT0hZ59g+4nP8ry2wt8FJ/j8/1HEuyuFrdk3kiD1KJDsLfCKlrLze75i0qM750ryxCT3Mfk2d7FzTYvfX8ndSibjaIGHHOhmI/i925SEsDQi0dB/Z6i51UYfXCjxv/nP5+R4olH9RwG7VbjZDhjuTfNYl/8/U7pDp52frECvU5Q95pUsROq/VJHT8vu6OfEyuXFCv2mo4QHUXhI6TQCXvZoOGyiond37F3s=
