sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: w+QKzADSjdk1EOGGd66Gz7kU/FH7vOFDu0TA+3cxtH/Aq+OY7sqLWegl7aJM4TdouDZffUlf9if+G6RyzsL9UbmmwOgC5QN30yCwmzLpnTRBFiEnEHXOIDJgSrRD7aqK9SFOIDFNfT1VswWuNi5fHnn4QWZFpXIF/6m4EUsPIG9Xt9cHfLyMsdZmezh0XimiOB2R/jkA6CoEMxDQy2B7uYTrPzkhBXlROBS7THdkRhLSYlw9/QymcTpZKU1/jLK/LGJlyCYzmsAXQKWUPfI4lNNd+elhAzcBkp2puqMmBEsWJsQi4JKwbMOJp8YZ8mk1gegvDozqJB0u5Yrn9P3EXFBRaEI1VsTqcTAllCIN0paEXV60xHaVcjOvLwBP+7o+kPGOrlfEtYwExZ2lwtC6h6KeUovR5ROiWHMts9LKDqPFnFiktNciPEuvc56RsbS6jTZ/8a3cYr/STQfCYbn06GyJD5pjtb0IONXn+zQAsRRTwHrnODgCkul/g6DnxbjH1a1kod0Oap8disl6OFYuJfdY/AYN2+1VwKmJwjWPfyy1tmr7J9Qi4vOrspLKyusSvib5ubJVK7oQ9amHD9J5/uWjt6DxNf0bMI/WqsUqjf8L2tlxpSpNtTkQPFoGi2J8BW8UVWlnBKSVitHa6mREJG2ua3tT+TcjcVsSH/1x2Ks=
  - secure: pda8fr3jOzV3Ic7zCPJjnt4g+bE086/L/rBlf+IyA9y0RASLbva6oQIWxE0k0iAGQspuejfEOpngB6JurJcSeHGiWV3VDFUfCvZFytoqPGqFj0W8VaLh2XFi0JTPvKzb5RBHMtyQMKi6wtCVV62Xxw4FwN6gpFGmBpmrTxC0EdamVLzCpr8wQ7ZBbsufXbRW8HuCZKxjmsqYCZkJUgTXvIasE55xqEjAG2Pis2gaKzN2ErURbMZ3hdkRHypJ1O1Ew5bOQ2LYMsqyZwjcdODc4m8kalyn0z7uB5c6cXjCXPyAdS0tsUWtio4oT7HKcS+JykD4ew7PuiVXdyx8omiIe7sLFzxLymdyARiSP1tqI5gtMvR6180pirbF+Dblx3ePViNMuc1MKgjrwuJ7sbmWGFONOiCFzdqTvANeTV1XwiG8wBIyNQlExSs8R9N8QJPQ+4p0DyGySvEIZUYnrvmRXICLmpybfRCgFj/gr3CPaD3QL+QU5G21KksZXEMYxZVYjjWsnV3CNnD1zVP46v44jL0zQaKVV3Zy8uTi6KqA4NFL1uzlIxE8pEWnNPa+Jl98PJBC6rTAda+S20qvbeXVoLnIkA+YugWei2y7tJKHOUfZLAygYrg1vNi6Q7qBrhZwaJQ/cs6vKdO9HC44MkuIgTgoBI93lGWkLDgNXI232qo=
